#
# docker network create --subnet 172.20.0.0/16 localstack-net
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack}"
    image: localstack/localstack-pro:4.12.0
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-ls-NoDExaTU-3636-wogu-GEnO-reBi96075c43}
      - ECS_REMOVE_CONTAINERS=0
      - ECR_ENDPOINT_STRATEGY=off 
      - ECS_DOCKER_FLAGS="--network=localstack-net --dns=172.20.0.2"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      localstack-net:
        ipv4_address: 172.20.0.2

networks:
  localstack-net:
    name: localstack-net
    ipam:
      config:
        # Specify the subnet range for IP address allocation
        - subnet: 172.20.0.0/16
